
#include "platform.h"
#include "board-clock.h"

void board_clock_init(void)
{
	/* Set HOCO (24M) and wait stable */
	write_mreg32(SYSREG2_HOCO_CFG, HOCO_24M);
	HARDWARE_REGISTER_WAIT(SYSREG2_HOCO_CFG, HOCO_24M | 1 << 4);

	/* Set PLL0 384M */
	/* 24M input clock */
	PLL0_CFG0->PLL_CFG0_b.PLL_REFIN_SEL = PLL_REF_MOSC;
	/* Output Clock = 24M /24 * 384 /1 =384M */
	PLL0_CFG0->PLL_CFG0_b.PLL_DM = 24;
	PLL0_CFG0->PLL_CFG0_b.PLL_DN = 384;
	PLL0_CFG0->PLL_CFG0_b.PLL_DP = 1;
	/* Power on */
	PLL0_CFG0->PLL_CFG0_b.PLL_PD = 0;
	PLL0_CFG0->PLL_CFG0_b.PLL_PDDP = 0;
	PLL0_CFG0->PLL_CFG0_b.PLL_RESETN = 1;
	HARDWARE_REGISTER_WAIT(PLL0_CFG0->PLL_CFG0_b.PLL_LOCK, 1);

	/* Set PLL1 96M */
	/* 24M input clock */
	PLL1_CFG0->PLL_CFG0_b.PLL_REFIN_SEL = PLL_REF_MOSC;
	/* Output Clock = 24M /24 * 384 /4 =96M */
	PLL1_CFG0->PLL_CFG0_b.PLL_DM = 24;
	PLL1_CFG0->PLL_CFG0_b.PLL_DN = 384;
	PLL1_CFG0->PLL_CFG0_b.PLL_DP = 4;
	/* Power on */
	PLL1_CFG0->PLL_CFG0_b.PLL_PD = 0;
	PLL1_CFG0->PLL_CFG0_b.PLL_PDDP = 0;
	PLL1_CFG0->PLL_CFG0_b.PLL_RESETN = 1;
	HARDWARE_REGISTER_WAIT(PLL1_CFG0->PLL_CFG0_b.PLL_LOCK, 1);

	/* Sys clock (96M) : M33 ,Bus, ROM, SRAM, DMA, CRYP*/
	SYS_CLK_SEL->CLK_SEL_b.CLK_SEL = BSP_CLOCKS_SOURCE_PLL1;
	SYS_CLK_SEL->CLK_SEL_b.CLK_DIV = 1;

	/* BLE bus clock (96M) : BLE base band, BLE Protocol Engine*/
	BLE_BUS_CLK_CFG->BLE_BUS_CLK_CFG_b.BLE_BUS_CLK_DIV = 1;

	/* Sys clock (384M) : QSPI*/
	QSPI_CORE_CLK_SEL->CLK_SEL_b.CLK_SEL = BSP_CLOCKS_SOURCE_PLL0;
	QSPI_CORE_CLK_SEL->CLK_SEL_b.CLK_DIV = 1;

	/* BLE clock (384M), BLE core */
	BLE_CLK_SEL->CLK_SEL_b.CLK_SEL = BSP_CLOCKS_SOURCE_PLL0;
	BLE_CLK_SEL->CLK_SEL_b.CLK_DIV = 1;

	/* USB clock (12M), usb phy */
	USB_CLK_CFG->USB_CLK_CFG_b.USBCLK_SEL = BSP_CLOCKS_SOURCE_MOSC;
	USB_CLK_CFG->USB_CLK_CFG_b.USBCLK_DIV = 2;

	/* PERI A clock (24M), UART */
	PERI_CLKA_SEL->CLK_SEL_b.CLK_SEL = BSP_CLOCKS_SOURCE_HOCO;
	PERI_CLKA_SEL->CLK_SEL_b.CLK_DIV = 1;

	/* PERI B clock (24M), WDT */
	PERI_CLKB_SEL->CLK_SEL_b.CLK_SEL = BSP_CLOCKS_SOURCE_HOCO;
	PERI_CLKB_SEL->CLK_SEL_b.CLK_DIV = 1;

	/* PERI C clock (24M), ADC */
	PERI_CLKC_SEL->CLK_SEL_b.CLK_SEL = BSP_CLOCKS_SOURCE_HOCO;
	PERI_CLKC_SEL->CLK_SEL_b.CLK_DIV = 1;

	/* PERI D clock (24M), DAC */
	PERI_CLKD_SEL->PERI_CLKD_SEL_b.PERICLKD_SEL = BSP_CLOCKS_SOURCE_HOCO;
	PERI_CLKD_SEL->PERI_CLKD_SEL_b.PERICLKD_DIV = 1;

	/* PERI E clock (24M), TIMER32, PWM */
	PERI_CLKE_SEL->CLK_SEL_b.CLK_SEL = BSP_CLOCKS_SOURCE_HOCO;
	PERI_CLKE_SEL->CLK_SEL_b.CLK_DIV = 1;

	/* Debounce clock clock (24M), IRQ, ADC, GPIO */
	DBCLK_CFG->CLK_SEL_b.CLK_SEL = BSP_CLOCKS_SOURCE_HOCO;
	DBCLK_CFG->CLK_SEL_b.CLK_DIV = 1;

	/* Trace clock (24M), CPU-OCD */
	TRACE_CLK_SEL->CLK_SEL_b.CLK_SEL = BSP_CLOCKS_SOURCE_HOCO;
	TRACE_CLK_SEL->CLK_SEL_b.CLK_DIV = 1;

	/* CLKOUT clock (12M), CLKOUT pin */
	CLK_OUT_SEL->CLK_SEL_b.CLK_SEL = BSP_CLOCKS_SOURCE_HOCO;
	CLK_OUT_SEL->CLK_SEL_b.CLK_DIV = 2;

	/* Low power clock (LPCLK) RTC, BLE, SysTick, GPIO, PMU, TSNS, VDT 32.768KHz */

}
